name: Docker Build, Push to DockerHub

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        # tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:latest
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:$(date +'%Y-%m-%d_%H-%M-%S' | env)
