name: Docker Build, Push to DockerHub

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
<<<<<<< HEAD
        
=======

>>>>>>> 305e2939a5690197059a60839516341f9305d148
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:latest

---
name: Deploy Python Flask App

on:
  push:
    branches:
    - 'python_app'

=======

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:latest

---
name: Deploy Python Flask App

on:
  push:
    branches:
    - 'python_app'

>>>>>>> 305e2939a5690197059a60839516341f9305d148
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and deploy
      env:
        FLASK_APP: app.py
      run: |
        flask build
        flask run
