name: Deploy Python Flask App
# name: Docker Build, Push to DockerHub

on:
  push:
    branches:
    - 'python_app'
#  pull_request:
#    branches:
#    - 'main'
        
jobs:

#  docker:
#    runs-on: ubuntu-latest
#    steps:
    
#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v2
    
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
     
#    - name: Login to Docker Hub
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
     
#    - name: Build and push
#      uses: docker/build-push-action@v4
#      with:
#        push: true
#        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:latest


  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4.7.0
#       with:
#         python-version: '3.8.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and deploy
      env:
        FLASK_APP: app.py
      run: |
        flask build
        flask run
        # flask run --host=0.0.0.0 --port=5000
